# Generated by Django 3.2.11 on 2022-06-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Latitude coordinates')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Longitude coordinates')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
